metros = float(input('Digite sua medida em metros:'))
print('A sua medida em Km é', (metros/1000))
print('A sua medida em Hm é', (metros/100))
print('A sua medida em Dam é', (metros/10))
print('A sua medida em dm é', (metros*10))
print('A sua medida em cm é', (metros*100))
print('A sua medida em mm é', (metros*1000))
